### ISSUE TITLE
[Question] On likelihood in delayed acceptance example

### ISSUE THREAD

**Issue by chaozg** [mikkelbue/tinyDA#5]
Hi there,

Thanks very much for making such a nice project! and Well done!

I have a tiny question about the likelihood on the coarse level in [Delayed acceptance example](https://github.com/mikkelbue/tinyDA/blob/main/examples/Delayed%20Acceptance.ipynb): why is `cov_likelihood_coarse` divided by `2`? Is it a typo or due to a particular reason?

```python
# In [9]
# define the likelihood
cov_likelihood_fine = sigma**2*np.eye(data_fine.size)
cov_likelihood_coarse = sigma**2*np.eye(data_coarse.size)/2
```

Regards,
Chao

**Comment by mikkelbue** [comment]
Hi @chaozg 

Thanks for spotting this! It is a typo. The original intention was to inflate the coarse likelihood to make it sample broader, but I got it backwards. It does not make any difference for the "correctness" of the results, however, since that is all corrected by the fine level Metropolis correction.

I have fixed this in https://github.com/mikkelbue/tinyDA/commit/2193cc019141855b13e86ddbef489b9da9b11a8b
